### PR TITLE
[WIP] Custom service-discovery for Prometheus

### PR DESCRIPTION
**Pull request by fzyzcjy**
See https://github.com/netdata/netdata/issues/9774 for details. Thanks!

### CODE REVIEW

**Comment by fzyzcjy** [comment]
Current status:

When open a terminal of the `netdata-child` pod, and use `cat /etc/netdata/go.d/sd/go.d.yml`, I do see those prometheus endpoints *correctly*. For example:

```
- module: prometheus
  name: prometheus-default_external-redis-metrics-5dc5d8d7c8-sq7fr_metrics_tcp_9121
  url: http://172.18.0.18:9121/metrics

- module: prometheus
  name: prometheus-default_tom-redis-cache-main-0_metrics_tcp_9121
  url: http://172.18.0.28:9121/metrics

- module: prometheus
  name: prometheus-default_tom-redis-cache-main-1_metrics_tcp_9121
  url: http://172.18.0.16:9121/metrics

- module: prometheus
  name: prometheus-default_tom-kafka-kafka-exporter-7978f8d9d6-zwjz7_tom-kafka-kafka-exporter_tcp_9404
  url: http://172.18.0.24:9404/metrics

- module: prometheus
  name: prometheus-default_tom-redis-cache-sentinel-2_metrics_tcp_9121
  url: http://172.18.0.19:9121/metrics

- module: prometheus
  name: prometheus-default_tom-redis-cache-sentinel-1_metrics_tcp_9121
  url: http://172.18.0.17:9121/metrics

- module: prometheus
  name: prometheus-default_tom-redis-cache-sentinel-0_metrics_tcp_9121
  url: http://172.18.0.27:9121/metrics

- module: coredns
  name: coredns-kube-system_coredns-66bff467f8-xxbrq_coredns_tcp_9153
  url: http://172.18.0.2:9153/metrics
```

Since I have several redis master, sentinal, and external redis exporter, kafka, etc, I do see each of them appearing here once. (The "0" in "-sentinel_0" is just because it is statefulset.) 

However, I do have a problem. Even if this file (`/etc/netdata/go.d/sd/go.d.yml`) seems to have the correct content, I *CANNOT* see anything in my netdata (visit ip:19999) child dashboard!

I did check the logs of netdata-child pod. But when I search "prometheus", it gives me *exactly zero result* (except one for springboot2 which is unrelated). 

Thus, I am completely confused. I see that, in go.d.plugin code, [prometheus](https://github.com/netdata/go.d.plugin/tree/e9030ed76e294b42e9a9add0ec886d7875dc70a9/pkg/prometheus) is in the `pkg` folder, while other guys such as `mysql` are in the `modules` folder. Thus, is it because the source code of go.d.plugin needs to be changed? Or just some simple mistake I make?

Thanks very much and Netdata is really wonderful to use!

**Comment by prologic** [comment]
@ilyam8 ☝️ for queries regarding no results shown under prometheus despite correct sd configs.

**Comment by ilyam8** [comment]
@fzyzcjy i am adding prometheus config in https://github.com/netdata/helmchart/pull/134 so i am closing this PR in favor of #134 (keep in mind #134 is blocked by netdata v1.25 release)

**Comment by ilyam8** [comment]
@fzyzcjy 

> When open a terminal of the netdata-child pod, and use cat /etc/netdata/go.d/sd/go.d.yml

cd to plugins.d

> ./go.d.plugin -d -c /etc/netdata/go.d/sd/go.d.yml -m prometheus

**Comment by fzyzcjy** [comment]
@ilyam8 Ah! Thus I should not do anything more right :/ Since you already made the pr

**Comment by OdysLam** [comment]
Hey @fzyzcjy, Odysseas here developer advocate in Netdata. Thanks so much for this PR, we love to see the community adding features to Netdata.

@ilyam8 is always one step ahead 😅, but we welcome contributions to a range of things. If you want to contribute, @ilyam8 can give you insights into collectors that we would love to have, but haven't yet found the time to develop.

Finally, welcome to our community 🙏

**Comment by fzyzcjy** [comment]
@OdysLam Thanks for your reply, do not worry I still love Netdata community :)

**Pull request closed without merging**
