### PR TITLE
Change master/slave to parent/child

### PR DESCRIPTION
**Pull request by ilyam8**
Fixes: #105

Tests:

- [X] ensure there is no error during manifests generation

```cmd
0 ilyam:helmchart (parent_child)$ helm template . > /dev/null; echo $?
0
```

- [X] ensure there is no master/slave in the repo

```cmd
0 ilyam:helmchart (parent_child)$ grep -i "slave" -R *
1 ilyam:helmchart (parent_child)$ grep -i "master" -R *
values.yaml:        role_recipients_slack[webmaster]="${DEFAULT_RECIPIENT_SLACK}"
```

- [X] ensure helm install works, parent/child netdata is up and running

```cmd
0 ilyam:helmchart (parent_child *)$ kubectl get pods -l app=netdata
NAME                  READY   STATUS    RESTARTS   AGE
netdata-child-ds5km   2/2     Running   0          2m43s
netdata-child-thskt   2/2     Running   0          2m43s
netdata-parent-0      1/1     Running   0          2m43s
```

### CODE REVIEW

**Comment by ilyam8** [comment]
@knatsakis 

i dont really understand [Chart versioning](https://helm.sh/docs/topics/charts/#the-chartyaml-file) we follow

> version: A SemVer 2 version (required)

[SemVer2 summary](https://semver.org/#summary)

```
MAJOR version when you make incompatible API changes,
MINOR version when you add functionality in a backwards compatible manner, and
PATCH version when you make backwards compatible bug fixes.
```

Are those changes incompatible API changes? Or we dont follow and i need to bump PATCH only?

**Comment by ilyam8** [comment]
should i bump `version` to `2.0.0` ?

**Comment by knatsakis** [comment]
I think that since the configuration changes in an backwards incompatible way, we should increase the MAJOR version.

Yes, I suggest you change the Helm chart's version to 2.0.0

**Comment by ilyam8** [comment]
a reminded @prologic 

> https://github.com/netdata/helmchart/deployments/activity_log?environment=github-pages

**Pull request merged**
