### PR TITLE
Add a GHA workflow for automating agent version updates.

### PR DESCRIPTION
**Pull request by Ferroin**
This adds a manually triggered workflow for generating PRs to update the version of the Netdata Agent provided by the Helm chart.

Short-term, this will be manually triggered during the release process, and will simply serve to speed things up a bit.

Longer-term, this will be automatically triggered by the release automation code in the agent repo once the Docker images have been published, reducing the amount of manual involvement required from the release manager.

### CODE REVIEW

**Comment by ilyam8** [comment]
To not alter seq value indentation i added

```diff
diff --git a/.github/scripts/update-agent-version.py b/.github/scripts/update-agent-version.py
index 6224e22..7dfd159 100644
--- a/.github/scripts/update-agent-version.py
+++ b/.github/scripts/update-agent-version.py
@@ -6,6 +6,11 @@ import sys
 import semver
 import yaml

+class MyDumper(yaml.Dumper):
+
+    def increase_indent(self, flow=False, indentless=False):
+        return super(MyDumper, self).increase_indent(flow, False)
+
 PREFIX = pathlib.PurePath('charts', 'netdata')

 NEW_APP_VERSION = sys.argv[1]
@@ -22,7 +27,7 @@ chart_data['version'] = str(new_chart_version)
 chart_data['appVersion'] = NEW_APP_VERSION

 with open(PREFIX.joinpath('Chart.yaml'), 'w') as chart:
-    chart.write(yaml.dump(chart_data, default_flow_style=False, sort_keys=False))
+    chart.write(yaml.dump(chart_data, Dumper=MyDumper, default_flow_style=False, sort_keys=False))

 with open(PREFIX.joinpath('README.md'), 'r+') as readme:
     data = readme.read()
```

---

executed 

> python .github/scripts/update-agent-version.py 4.4.4

```diff
diff --git a/charts/netdata/Chart.yaml b/charts/netdata/Chart.yaml
index e06e417..f7e4e9c 100644
--- a/charts/netdata/Chart.yaml
+++ b/charts/netdata/Chart.yaml
@@ -1,6 +1,6 @@
 apiVersion: v2
 name: netdata
-version: 3.5.1
+version: 3.5.2
 description: Real-time performance monitoring, done right!
 type: application
 keywords:
@@ -25,4 +25,4 @@ maintainers:
   - name: Oleksii Kravchenko
     email: kamikaze.ua@gmail.com
 icon: https://netdata.github.io/helmchart/logo.png
-appVersion: v1.29.1
+appVersion: 4.4.4
diff --git a/charts/netdata/README.md b/charts/netdata/README.md
index 0ce83e7..9111997 100644
--- a/charts/netdata/README.md
+++ b/charts/netdata/README.md
@@ -1,6 +1,6 @@
 # Netdata Helm chart for Kubernetes deployments

-[![Artifact HUB](https://img.shields.io/endpoint?url=https://artifacthub.io/badge/repository/netdata)](https://artifacthub.io/packages/search?repo=netdata) ![Version: 3.5.1](https://img.shields.io/badge/Version-3.5.1-informational) ![AppVersion: v1.29.1](https://img.shields.io/badge/AppVersion-v1.29.1-informational)
+[![Artifact HUB](https://img.shields.io/endpoint?url=https://artifacthub.io/badge/repository/netdata)](https://artifacthub.io/packages/search?repo=netdata) ![Version: 3.5.2](https://img.shields.io/badge/Version-3.5.2-informational) ![AppVersion: 4.4.4](https://img.shields.io/badge/AppVersion-4.4.4-informational)

 _Based on the work of varyumin (https://github.com/varyumin/netdata)_.

@@ -84,7 +84,7 @@ The following table lists the configurable parameters of the netdata chart and t
 |------------------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------|---------------------------------------------------------------------------|
 | `replicaCount`                           | Number of `replicas` for the parent netdata `Deployment`                                                                                               | `1`                                                                       |
 | `image.repository`                       | Container image repo                                                                                                                                   | `netdata/netdata`                                                         |
-| `image.tag`                              | Container image tag                                                                                                                                    | Latest stable netdata release (e.g. `v1.29.1`)                            |
+| `image.tag`                              | Container image tag                                                                                                                                    | Latest stable netdata release (e.g. `4.4.4`)                            |
 | `image.pullPolicy`                       | Container image pull policy                                                                                                                            | `Always`                                                                  |
 | `service.type`                           | Parent service type                                                                                                                                    | `ClusterIP`                                                               |
 | `service.port`                           | Parent service port                                                                                                                                    | `19999`                                                                   |
```

**Comment by Ferroin** [comment]
> To not alter seq value indentation [i added](https://stackoverflow.com/questions/25108581/python-yaml-dump-bad-indentation)
> 
> ```diff
> diff --git a/.github/scripts/update-agent-version.py b/.github/scripts/update-agent-version.py
> index 6224e22..7dfd159 100644
> --- a/.github/scripts/update-agent-version.py
> +++ b/.github/scripts/update-agent-version.py
> @@ -6,6 +6,11 @@ import sys
>  import semver
>  import yaml
> 
> +class MyDumper(yaml.Dumper):
> +
> +    def increase_indent(self, flow=False, indentless=False):
> +        return super(MyDumper, self).increase_indent(flow, False)
> +
>  PREFIX = pathlib.PurePath('charts', 'netdata')
> 
>  NEW_APP_VERSION = sys.argv[1]
> @@ -22,7 +27,7 @@ chart_data['version'] = str(new_chart_version)
>  chart_data['appVersion'] = NEW_APP_VERSION
> 
>  with open(PREFIX.joinpath('Chart.yaml'), 'w') as chart:
> -    chart.write(yaml.dump(chart_data, default_flow_style=False, sort_keys=False))
> +    chart.write(yaml.dump(chart_data, Dumper=MyDumper, default_flow_style=False, sort_keys=False))
> 
>  with open(PREFIX.joinpath('README.md'), 'r+') as readme:
>      data = readme.read()
> ```
> 
> executed
> 
> > python .github/scripts/update-agent-version.py 4.4.4
> 
> ```diff
> diff --git a/charts/netdata/Chart.yaml b/charts/netdata/Chart.yaml
> index e06e417..f7e4e9c 100644
> --- a/charts/netdata/Chart.yaml
> +++ b/charts/netdata/Chart.yaml
> @@ -1,6 +1,6 @@
>  apiVersion: v2
>  name: netdata
> -version: 3.5.1
> +version: 3.5.2
>  description: Real-time performance monitoring, done right!
>  type: application
>  keywords:
> @@ -25,4 +25,4 @@ maintainers:
>    - name: Oleksii Kravchenko
>      email: kamikaze.ua@gmail.com
>  icon: https://netdata.github.io/helmchart/logo.png
> -appVersion: v1.29.1
> +appVersion: 4.4.4
> diff --git a/charts/netdata/README.md b/charts/netdata/README.md
> index 0ce83e7..9111997 100644
> --- a/charts/netdata/README.md
> +++ b/charts/netdata/README.md
> @@ -1,6 +1,6 @@
>  # Netdata Helm chart for Kubernetes deployments
> 
> -[Artifact HUB](https://artifacthub.io/packages/search?repo=netdata) Version: 3.5.1 AppVersion: v1.29.1
> +[Artifact HUB](https://artifacthub.io/packages/search?repo=netdata) Version: 3.5.2 AppVersion: 4.4.4
> 
>  _Based on the work of varyumin (https://github.com/varyumin/netdata)_.
> 
> @@ -84,7 +84,7 @@ The following table lists the configurable parameters of the netdata chart and t
>  |------------------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------|---------------------------------------------------------------------------|
>  | `replicaCount`                           | Number of `replicas` for the parent netdata `Deployment`                                                                                               | `1`                                                                       |
>  | `image.repository`                       | Container image repo                                                                                                                                   | `netdata/netdata`                                                         |
> -| `image.tag`                              | Container image tag                                                                                                                                    | Latest stable netdata release (e.g. `v1.29.1`)                            |
> +| `image.tag`                              | Container image tag                                                                                                                                    | Latest stable netdata release (e.g. `4.4.4`)                            |
>  | `image.pullPolicy`                       | Container image pull policy                                                                                                                            | `Always`                                                                  |
>  | `service.type`                           | Parent service type                                                                                                                                    | `ClusterIP`                                                               |
>  | `service.port`                           | Parent service port                                                                                                                                    | `19999`                                                                   |
> ```

Thanks for the suggestion, but I just updated it to use https://pypi.org/project/ruamel.yaml/.

**Comment by ilyam8** [comment]
@Ferroin do we stil need https://github.com/netdata/helmchart/blob/master/tools/update_helmchart.sh after this PR?

**Comment by Ferroin** [comment]
> @Ferroin do we stil need https://github.com/netdata/helmchart/blob/master/tools/update_helmchart.sh after this PR?

Nice catch, I had completely forgotten about that script. We should not need it anymore once this PR is merged.

**Comment by ilyam8** [comment]
Perhaps remove it in this PR? i bet if we don't do it will be hanging here for a while 😄

**Comment by Ferroin** [comment]
Yeah, I’ll add a commit once I’m back from lunch to drop it in this PR.

**Review by knatsakis — APPROVED** [review]
Nice work @Ferroin. Just make sure you remove https://github.com/netdata/helmchart/blob/master/tools/update_helmchart.sh

Thanks!

**Review by ilyam8 — APPROVED** [review]

**Review by knatsakis — APPROVED** [review]

**Pull request merged**
