### PR TITLE
Add Github Actions Workflows to automate Helm Chart Releases

### LINKED ISSUE #74: Make GitHub repo directly useable from Helm
Hi,
Until this is added to the official helm packages, it might be nice to have the helm Chart useable via this git repo as a helm repo?
I would like to install this using my terraform helm provider.
e.g. this should exist: https://raw.githubusercontent.com/netdata/helmchart/master/index.yaml

Ref https://github.com/netdata/helmchart/issues/72

### PR DESCRIPTION
**Pull request by prologic**
This now effectively gives us an official Helm Chart Repo.

Along with #127 we also have a nice looking landing page for it too!

Closes #74

### CODE REVIEW

**Comment by ncmans** [comment]
@prologic can we see if we can keep the directory structure as not to break anyone's pipeline that depends on chart being on the root of the repo.

**Comment by prologic** [comment]
> @prologic can we see if we can keep the directory structure as not to break anyone's pipeline that depends on chart being on the root of the repo.

I _can_ try but that will take significant more work...

**Review by ncmans — COMMENTED** [review]
> I _can_ try but that will take significant more work...

It shouldn't, but if it does, can you please check all references of docs to the helmchart to ensure they will continue to be valid after this PR is merged.

**Review by knatsakis — APPROVED** [review]

**Comment by prologic** [comment]
Thanks @knatsakis Unfortunately this doesn't quite work yet, and I'm working with upstream on this. But I _think_ the problem here in fact is that the structure of this repo _was always_ wrong and we _may_ have to change it in the end. See [this comment](https://github.com/helm/chart-releaser-action/issues/36#issuecomment-689487818)

**Comment by kam1kaze** [comment]
@prologic What did you decide? Are you going to change the repo structure? I think I could help with such PR that it works with the current structure.

**Comment by prologic** [comment]
> @prologic What did you decide? Are you going to change the repo structure? I think I could help with such PR that it works with the current structure.

I'm back on this and I will just restructure our repo to fit within the accept documented structure.

**Comment by prologic** [comment]
Redone and superseded by #153

**Pull request closed without merging**
