### PR TITLE
add ability to manage custom configs

### PR DESCRIPTION
**Pull request by kam1kaze**
Hi,

I don't like to modify the source code of the helm package, if I need to enable some plugin. So I add such possibility.

Thanks

### CODE REVIEW

**Comment by kam1kaze** [comment]
I thought about this, but it is a breaking change for the helm package. But if it's ok for you, I'll update the PR.

**Comment by cakrit** [comment]
Make the version 1.0.0 then. It's much better and cleaner the way you did it. We just need to be careful to change the major version for every breaking change.

**Comment by cakrit** [comment]
Merging and I'll do some more updates to the README, along with the change to include v1.15.0.

**Comment by kam1kaze** [comment]
@cakrit ок, thanks. I forgot about README :)

**Comment by cakrit** [comment]
Don't worry about it, great job mate. I'm adding you to the maintainers too in Charts.yaml. If you like, drop me an email so I can add your email too (chris@netdata.cloud), otherwise I'll just leave your name there (hoping it doesn't break helm).

**Pull request merged**
