### PR TITLE
Add a official helm chart repo landing page

### LINKED ISSUE #74: Make GitHub repo directly useable from Helm
Hi,
Until this is added to the official helm packages, it might be nice to have the helm Chart useable via this git repo as a helm repo?
I would like to install this using my terraform helm provider.
e.g. this should exist: https://raw.githubusercontent.com/netdata/helmchart/master/index.yaml

Ref https://github.com/netdata/helmchart/issues/72

### PR DESCRIPTION
**Pull request by prologic**
- Closes #74 

Screen Shot 2020-08-12 at 15 35 34

### CODE REVIEW

**Review by ncmans — APPROVED** [review]
Needs to wait for helm repo PR to go in first.

**Comment by prologic** [comment]
Yup I'm working on it!

**Review by knatsakis — APPROVED** [review]

**Comment by prologic** [comment]
Guys we _have_ to restructure out repo after-all. It was never created with the _correct_ layout in the first place. I'm not certain it won't break or affect anyone's tooling that _may_ rely on the old/wrong structure, but I have no way to be sure.

**Comment by knatsakis** [comment]
@prologic, I would propose to go ahead and do any changes necessary.

The existing, minimal "helm repo" is not official (I believe it was never announced or discussed) and since it is for internal use only, we will fix whatever needs fixing in order to work with a proper *official* helm repo.

**Comment by prologic** [comment]
Agreed, I will work on this tomorrow in that case. Added to my "ToDo"

**Comment by prologic** [comment]
Redone and super-ceded by #152

**Pull request closed without merging**
