### PR TITLE
Persistence toggle and fixes

### LINKED ISSUE #17: Provide persistence option in values.yml
There should be an option to create no persistent storage at all, e.g. when using the master instance for prometheus scraping only.

### PR DESCRIPTION
**Pull request by karuppiah7890**
Fixes #17 and #25 

Summary of the features and fixes
1. Support toggling of persistence volumes for database and alarms
2. Fix `master.alarms.storageclass` being used for claiming volume for database too
3. Add apiVersion in Chart.yaml as it's required in helm3 and canary version of helm2 also shows linting error for the same
4. Fix `maintainers` key in Chart.yaml
5. Fix env field being in pod spec instead of inside container spec, in both DaemonSet and StatefulSet

cc @cakrit @varyumin . Please review 😄

### CODE REVIEW

**Comment by karuppiah7890** [comment]
Sure! 😄  And I put two commits. Should I change the Chart version in both the commits? Then the version would be 0.0.14 . One is a feature and the other is a fix. So I think two version bumps is okay

**Comment by cakrit** [comment]
No need to make it .14, it's just one PR, resulting in a new version. 
I'll be changing to 1.0.0 anyway tomorrow or on Monday, after I put in the tag 1.15.0

**Comment by karuppiah7890** [comment]
Pushed the appropriate changes 😄 version is 0.0.13

**Comment by cakrit** [comment]
And it's in! Thanks @karuppiah7890 !!!

**Comment by karuppiah7890** [comment]
🎉 Yay! Thanks @cakrit 😁

**Pull request merged**
