### PR TITLE
Create .helmignore

### PR DESCRIPTION
**Pull request by ilyam8**
Fixes: #88

### CODE REVIEW

**Comment by ilyam8** [comment]
i think i am wrong and the file should be in a user directory 🤔

**Comment by ilyam8** [comment]
@lgg42

can you test this?

i am not really sure it works, related: https://github.com/helm/helm/issues/1674

**Comment by lgg42** [comment]
> @lgg42
> 
> can you test this?
> 
> i am not really sure it works, related: [helm/helm#1674](https://github.com/helm/helm/issues/1674)

Is working for me :-)

**helm install command**
`helm upgrade netdata . -i --wait --namespace kube-system --atomic --cleanup-on-fail --recreate-pods -f ../values/netdata.yaml`

**tiller logs**
```
[tiller] 2020/04/23 21:30:22 getting history for release netdata
[storage] 2020/04/23 21:30:22 getting release history for "netdata"
[tiller] 2020/04/23 21:30:22 preparing install for netdata
[storage] 2020/04/23 21:30:22 getting release history for "netdata"
2020/04/23 21:30:22 Warning: Merging destination map for chart 'netdata'. The destination item 'tolerations' is a table and ignoring the source 'tolerations' as it has a non-table value of: []
[tiller] 2020/04/23 21:30:22 rendering netdata chart using values
[tiller] 2020/04/23 21:30:22 performing install for netdata
[tiller] 2020/04/23 21:30:22 executing 0 crd-install hooks for netdata
[tiller] 2020/04/23 21:30:22 hooks complete for crd-install netdata
[tiller] 2020/04/23 21:30:22 executing 0 pre-install hooks for netdata
[tiller] 2020/04/23 21:30:22 hooks complete for pre-install netdata
[storage] 2020/04/23 21:30:22 getting release history for "netdata"
[storage] 2020/04/23 21:30:22 creating release "netdata.v1"
[kube] 2020/04/23 21:30:22 building resources from manifest
[kube] 2020/04/23 21:30:22 creating 12 resource(s)
[kube] 2020/04/23 21:30:23 beginning wait for 12 resources with timeout of 5m0s
[kube] 2020/04/23 21:30:25 Pod is not ready: kube-system/netdata-slave-5q2gs
[kube] 2020/04/23 21:30:27 Pod is not ready: kube-system/netdata-slave-5q2gs
[kube] 2020/04/23 21:30:29 Pod is not ready: kube-system/netdata-slave-5q2gs
[kube] 2020/04/23 21:30:31 Pod is not ready: kube-system/netdata-slave-5q2gs
[kube] 2020/04/23 21:30:33 Pod is not ready: kube-system/netdata-slave-5q2gs
[kube] 2020/04/23 21:30:35 Pod is not ready: kube-system/netdata-slave-5q2gs
[kube] 2020/04/23 21:30:37 Pod is not ready: kube-system/netdata-slave-5q2gs
[kube] 2020/04/23 21:30:39 Pod is not ready: kube-system/netdata-slave-5q2gs
[kube] 2020/04/23 21:30:41 Pod is not ready: kube-system/netdata-slave-5q2gs
[tiller] 2020/04/23 21:30:43 executing 0 post-install hooks for netdata
[tiller] 2020/04/23 21:30:43 hooks complete for post-install netdata
[storage] 2020/04/23 21:30:43 updating release "netdata.v1"
[storage] 2020/04/23 21:30:43 getting last revision of "netdata"
[storage] 2020/04/23 21:30:43 getting release history for "netdata"
[kube] 2020/04/23 21:30:43 Doing get for PodSecurityPolicy: "netdata-psp"
[kube] 2020/04/23 21:30:43 get relation pod of object: /PodSecurityPolicy/netdata-psp
[kube] 2020/04/23 21:30:43 Doing get for ConfigMap: "netdata-conf-master"
[kube] 2020/04/23 21:30:43 get relation pod of object: kube-system/ConfigMap/netdata-conf-master
[kube] 2020/04/23 21:30:43 Doing get for ConfigMap: "netdata-conf-slave"
[kube] 2020/04/23 21:30:43 get relation pod of object: kube-system/ConfigMap/netdata-conf-slave
[kube] 2020/04/23 21:30:43 Doing get for ServiceAccount: "netdata"
[kube] 2020/04/23 21:30:43 get relation pod of object: kube-system/ServiceAccount/netdata
[kube] 2020/04/23 21:30:43 Doing get for ClusterRole: "netdata"
[kube] 2020/04/23 21:30:43 get relation pod of object: /ClusterRole/netdata
[kube] 2020/04/23 21:30:43 Doing get for ClusterRole: "netdata-psp"
[kube] 2020/04/23 21:30:43 get relation pod of object: /ClusterRole/netdata-psp
[kube] 2020/04/23 21:30:43 Doing get for ClusterRoleBinding: "netdata"
[kube] 2020/04/23 21:30:43 get relation pod of object: /ClusterRoleBinding/netdata
[kube] 2020/04/23 21:30:43 Doing get for ClusterRoleBinding: "netdata-psp"
[kube] 2020/04/23 21:30:43 get relation pod of object: /ClusterRoleBinding/netdata-psp
[kube] 2020/04/23 21:30:43 Doing get for Service: "netdata"
[kube] 2020/04/23 21:30:43 get relation pod of object: kube-system/Service/netdata
[kube] 2020/04/23 21:30:43 Doing get for DaemonSet: "netdata-slave"
[kube] 2020/04/23 21:30:43 get relation pod of object: kube-system/DaemonSet/netdata-slave
[kube] 2020/04/23 21:30:43 Doing get for StatefulSet: "netdata-master"
[kube] 2020/04/23 21:30:43 get relation pod of object: kube-system/StatefulSet/netdata-master
[kube] 2020/04/23 21:30:43 Doing get for Ingress: "netdata"
[kube] 2020/04/23 21:30:43 get relation pod of object: kube-system/Ingress/netdata
```

If I remove the .helmignore it fails again...

**tiller logs**
```
[storage/driver] 2020/04/23 21:33:44 create: failed to create: ConfigMap "netdata.v1" is invalid: []: Too long: must have at most 1048576 characters
[tiller] 2020/04/23 21:33:44 warning: Failed to record release netdata: ConfigMap "netdata.v1" is invalid: []: Too long: must have at most 1048576 characters
```

**helm command**
```
$ helm upgrade netdata . -i --wait --namespace kube-system --atomic --cleanup-on-fail --recreate-pods -f ../values/netdata.yaml 
Release "netdata" does not exist. Installing it now.
NAME:   netdata
Error: getting deployed release "netdata": release: "netdata" not found
```

**Comment by ilyam8** [comment]
@lgg42 perfect 🎉  thx for testing

**Pull request merged**
